services:
  frontend:
    image: wmm-frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    restart: always
  backend:
    image: wmm-backend
    ports:
      - 8000:8000
    restart: always