# Generated by Django 5.0.1 on 2024-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(verbose_name='date_added')),
                ('genre', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=150)),
                ('duration', models.IntegerField(max_length=5)),
            ],
        ),
    ]
