# Generated by Django 5.0.3 on 2024-04-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cover',
            new_name='cover_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
