# Generated by Django 5.0.3 on 2024-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_cover_link_movie_cover_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
