# Generated by Django 5.0.3 on 2024-04-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_cover_alter_movie_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cover',
            new_name='cover_link',
        ),
    ]
