# Generated by Django 5.0.3 on 2024-04-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_cover_movie_cover_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('night_date', models.DateTimeField(verbose_name='night_date')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
