# Generated by Django 5.0.2 on 2024-04-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movienight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
