# Generated by Django 5.0.3 on 2024-06-26 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_cover_link_movie_duration_movie_is_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienight',
            name='selected_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
