# Generated by Django 5.0.3 on 2024-07-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movienight_selected_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_watched',
        ),
    ]
