# Generated by Django 5.0.2 on 2024-09-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movienight_selected_movie'),
        ('movies', '0012_registerquestion'),
    ]

    operations = [
    ]
