# Generated by Django 5.0.2 on 2024-10-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_merge_20240905_2248'),
    ]

    operations = [
    ]
