# Generated by Django 5.0.2 on 2024-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_merge_20241026_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
