# Generated by Django 5.0.2 on 2024-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
