# Generated by Django 5.0.2 on 2025-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerquestion',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, unique=True),
        ),
    ]
