# Generated by Django 5.0.2 on 2025-07-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_registerquestion_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienight',
            name='movie_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
