name: Frontend Code Quality Checks

on:
  pull_request:
    paths:
      - 'frontend/src/**'

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Prettier check
        working-directory: ./frontend
        run: npm run prettier:check

      - name: Run ESLint check
        working-directory: ./frontend
        run: npm run lint

      - name: Display message if checks fail
        if: failure()
        run: |
          echo "Code quality checks failed. Please run the following commands in the frontend directory to fix issues:"
          echo "  - npm run prettier:format"
          echo "  - npm run eslint:fix"
